// ============================================================================
// Water quality presets — apply groups of water settings at once.
// ============================================================================

import { WATER_DEFAULT_PARAMS } from './WaterSettings.js';

export const WATER_PRESETS = {
  legacy: {
    label: '레거시 낮음',
    patch: {
      waterMode: 'legacy',
      waterQualityPreset: 'legacy',
      waterFoamEnabled: true,
      waterFoamStrength: 0.75,
    },
  },
  balanced: {
    label: '밸런스 리얼리스틱',
    patch: {
      waterMode: 'realistic',
      waterQualityPreset: 'balanced',
      waterOpacity: 0.72,
      waterRoughness: 0.3,
      waterRefractionStrength: 0.45,
      waterSpecularStrength: 1.0,
      waterDepthColorStrength: 1.0,
      waterDepthOpacityStrength: 1.0,
      waterAbsorptionStrength: 0.95,
      waterWaveScale: 1.0,
      waterWaveStrength: 1.0,
      waterSmallWaveStrength: 0.65,
      waterLargeWaveStrength: 1.0,
      waterNormalIntensity: 1.0,
      waterNormalResolution: 1.0,
      waterFoamEnabled: true,
      waterFoamStrength: 0.7,
      waterFresnelStrength: 1.0,
      waterReflectionQuality: 1.0,
      waterUnderwaterEnabled: true,
      waterCausticsQuality: 0.3,
    },
  },
  tropical: {
    label: '맑은 열대',
    patch: {
      waterMode: 'realistic',
      waterQualityPreset: 'tropical',
      waterOpacity: 0.48,
      waterRoughness: 0.2,
      waterSpecularStrength: 1.1,
      waterDepthColorStrength: 0.85,
      waterDepthOpacityStrength: 0.7,
      waterMaxVisibleDepth: 90,
      waterShallowDistance: 12,
      waterDeepDistance: 45,
      waterAbsorptionStrength: 0.6,
      waterWaveStrength: 0.72,
      waterSmallWaveStrength: 0.5,
      waterLargeWaveStrength: 0.72,
      waterNormalIntensity: 0.8,
      waterNormalResolution: 0.9,
      waterFoamStrength: 0.55,
      waterFresnelStrength: 1.1,
      waterRefractionStrength: 0.55,
      waterReflectionQuality: 1.0,
    },
  },

  cartoon: {
    label: '만화 물',
    patch: {
      waterMode: 'legacy',
      waterQualityPreset: 'cartoon',
      waterOpacity: 0.78,
      waterRoughness: 0.18,
      waterFresnelStrength: 1.35,
      waterRefractionStrength: 0.25,
      waterSpecularStrength: 0.85,
      waterDepthColorStrength: 0.65,
      waterDepthOpacityStrength: 0.55,
      waterMaxVisibleDepth: 80,
      waterShallowDistance: 14,
      waterDeepDistance: 38,
      waterAbsorptionStrength: 0.55,
      waterWaveSpeed: 0.55,
      waterWaveScale: 1.65,
      waterWaveStrength: 0.34,
      waterSmallWaveStrength: 0.18,
      waterLargeWaveStrength: 0.28,
      waterNormalIntensity: 0.45,
      waterFoamEnabled: true,
      waterFoamStrength: 1.15,
      waterFoamWidth: 5.6,
      waterFoamSoftness: 0.35,
      waterFoamAnimSpeed: 0.55,
      waterSlopeFoam: 0.15,
      waterCliffFoam: 0.18,
      waterUnderwaterMode: 'lite',
      waterUnderwaterFogDensity: 0.75,
      waterUnderwaterVisibility: 1.25,
      waterUnderwaterDistortion: 0.25,
      waterUnderwaterCaustics: 0.25,
      waterReflectionQuality: 0.35,
      waterRefractionQuality: 0.25,
      waterFoamQuality: 0.8,
      waterCausticsQuality: 0.2,
      waterNormalResolution: 0.5,
      waterRenderScale: 0.75,
    },
  },
  ocean: {
    label: '심해',
    patch: {
      waterMode: 'realistic',
      waterQualityPreset: 'ocean',
      waterOpacity: 0.88,
      waterRoughness: 0.22,
      waterRefractionStrength: 0.35,
      waterSpecularStrength: 1.15,
      waterDepthColorStrength: 1.25,
      waterDepthOpacityStrength: 1.15,
      waterMaxVisibleDepth: 160,
      waterShallowDistance: 6,
      waterDeepDistance: 80,
      waterAbsorptionStrength: 1.35,
      waterWaveStrength: 1.2,
      waterLargeWaveStrength: 1.25,
      waterSmallWaveStrength: 0.72,
      waterNormalIntensity: 1.05,
      waterNormalResolution: 1.1,
      waterFoamStrength: 0.65,
      waterFresnelStrength: 0.9,
      waterReflectionQuality: 1.1,
    },
  },
  lake: {
    label: '산 속 호수',
    patch: {
      waterMode: 'realistic',
      waterQualityPreset: 'lake',
      waterOpacity: 0.66,
      waterRoughness: 0.44,
      waterRefractionStrength: 0.5,
      waterSpecularStrength: 0.8,
      waterDepthColorStrength: 0.95,
      waterDepthOpacityStrength: 0.9,
      waterMaxVisibleDepth: 70,
      waterShallowDistance: 10,
      waterDeepDistance: 40,
      waterAbsorptionStrength: 0.9,
      waterWaveScale: 0.9,
      waterWaveStrength: 0.45,
      waterSmallWaveStrength: 0.35,
      waterLargeWaveStrength: 0.5,
      waterNormalIntensity: 0.72,
      waterNormalResolution: 0.8,
      waterFoamStrength: 0.4,
      waterFoamWidth: 2.4,
      waterReflectionQuality: 0.95,
    },
  },
  swamp: {
    label: '늪 물',
    patch: {
      waterMode: 'realistic',
      waterQualityPreset: 'swamp',
      waterRoughness: 0.58,
      waterRefractionStrength: 0.2,
      waterSpecularStrength: 0.55,
      waterDepthColorStrength: 1.1,
      waterDepthOpacityStrength: 1.25,
      waterMaxVisibleDepth: 35,
      waterAbsorptionStrength: 1.5,
      waterOpacity: 0.94,
      waterWaveStrength: 0.28,
      waterSmallWaveStrength: 0.2,
      waterLargeWaveStrength: 0.35,
      waterNormalIntensity: 0.55,
      waterNormalResolution: 0.55,
      waterFoamStrength: 0.35,
      waterReflectionQuality: 0.65,
      waterUnderwaterFogDensity: 1.4,
      waterUnderwaterVisibility: 0.55,
    },
  },
  alien: {
    label: '에일리언 물',
    patch: {
      waterMode: 'volumetric',
      waterQualityPreset: 'alien',
      waterDepthColorStrength: 1.3,
      waterFresnelStrength: 1.4,
      waterRefractionStrength: 0.7,
      waterFoamStrength: 0.5,
      waterUnderwaterCaustics: 0.8,
      waterCausticsQuality: 0.85,
    },
  },
  volumetric: {
    label: '고해상도 볼류메트릭',
    patch: {
      waterMode: 'volumetric',
      waterQualityPreset: 'volumetric',
      waterOpacity: 0.8,
      waterRoughness: 0.24,
      waterRefractionStrength: 0.58,
      waterSpecularStrength: 1.1,
      waterDepthColorStrength: 1.15,
      waterDepthOpacityStrength: 1.1,
      waterAbsorptionStrength: 1.2,
      waterFoamStrength: 0.85,
      waterFoamQuality: 1.2,
      waterRefractionQuality: 0.75,
      waterRenderScale: 1.0,
      waterCausticsQuality: 0.65,
      waterUnderwaterCaustics: 0.55,
      waterNormalIntensity: 1.15,
      waterNormalResolution: 1.15,
      waterReflectionQuality: 1.0,
    },
  },
  cinematic: {
    label: '시네마틱 스크린샷',
    patch: {
      waterMode: 'cinematic',
      waterQualityPreset: 'cinematic',
      waterOpacity: 0.82,
      waterRoughness: 0.18,
      waterRefractionStrength: 0.62,
      waterSpecularStrength: 1.25,
      waterDepthColorStrength: 1.2,
      waterFoamStrength: 1.0,
      waterFoamQuality: 1.5,
      waterReflectionQuality: 1.4,
      waterRefractionQuality: 1.0,
      waterRenderScale: 2.0,
      waterUpdateFrequency: 1,
      waterCausticsQuality: 1.0,
      waterNormalIntensity: 1.25,
      waterNormalResolution: 1.35,
      waterLargeWaveStrength: 1.15,
      waterUnderwaterCaustics: 0.7,
    },
  },
};

export function applyWaterPreset(params, presetKey) {
  const preset = WATER_PRESETS[presetKey];
  if (!preset) return params;
  return {
    ...params,
    waterEnabled: preset.patch.waterMode !== 'off',
    ...preset.patch,
    waterQualityPreset: presetKey,
  };
}

export function resetWaterSettings(params) {
  const next = { ...params };
  for (const key of Object.keys(WATER_DEFAULT_PARAMS)) {
    next[key] = WATER_DEFAULT_PARAMS[key];
  }
  return next;
}
